### ISSUE TITLE
[Enhancement] - Add Tabs and better control over the menu layout

### ISSUE THREAD

**Issue by TBiscuit1** [DarwinBaker/AATool#14]
So there is the problem of the resolution that is FAT. But here is a simple solution, why not adding tabs so you can choose which achivement group you want to show? This would also come with the possibility to edit the layout (without going through the files and edit it manually) and would make mod compatibility easier for everyone!

(Btw, would have LOVED to help you with coding that but my Java knowledge is limited to only If statement, Tables, Whiles and Functions/Objects... Still learning more tho!)

**Comment by DarwinBaker** [comment]
I like the idea of tabs, but probably for something else in the future. The layout is already editable, and resolutions below 1280x720 will not be supported
