### ISSUE TITLE
Missing Who Is Cutting Onions?

### ISSUE THREAD

**Issue by gible** [DarwinBaker/AATool#15]
Missing the advancement Who Is Cutting Onions? obtained after getting some Crying Obsidian.

![image](https://user-images.githubusercontent.com/42523148/146666351-36888076-cd4d-4eea-869f-e50723e24e3b.png)

**Comment by DarwinBaker** [comment]
Sorry, I'm not entirely clear what the issue is. Would you mind clarifying with some more information? "Who is cutting onions?" is definitely on the tracker, and it definitely works:
![image](https://user-images.githubusercontent.com/51175243/146683429-4482871e-4d49-404e-9092-0839cf0031b5.png)

**Comment by gible** [comment]
PEBKAC. Sorry!
