### ISSUE TITLE
Crash on JSON read error

### ISSUE THREAD

**Issue by mcmonkey819** [DarwinBaker/AATool#17]
I setup AATool to track advancements for a shared world I'm playing with my family. It took some effort to get the server FTP folder mounted as a drive (and I will +1 the feature request for FTP support), but once I could mount the folder I could see the advancements. 

Then suddenly, the tool started crashing. I looked at the the log file and it indicated a JSON parsing error, so I found the offending file and line (error was on line 1134) and loaded it into a couple of JSON viewers and there were no formatting errors with the JSON. I couldn't spot anything out of place about the JSON object, so on a hunch I copied the timestamp from the previous object and overwrote the one causing the error and this resolved the problem.

I wanted to report the issue and provide the unmodified failing JSON file for investigation in case other people end up with this issue.
[Link to failing JSON](https://pastebin.com/yPXQZpdx)

**Comment by DarwinBaker** [comment]
Unable to reproduce with provided json
