### ISSUE TITLE
Allow to filter players

### ISSUE THREAD

**Issue by TheKingDave** [DarwinBaker/AATool#18]
I use this tool to track my advancement progress on my own server where I play with some friends.
I track the advancements using SFTP.

Sadly the tool does not only show my advancements but the advancements of all players.

An option to only show advancements of a single player would be great.

![aatool](https://user-images.githubusercontent.com/9198553/150188867-c4b0f1ef-2ee8-4480-a719-52d9fbfe06fa.jpg)

For example, I don't have the advancement "Hidden in the Depths". I also never had more than 1 Wither Skulls.
For "Adventureing Time" and "Monsters Hunted" I know I can change the displayed Player but it resets everytime it syncs with the server.

**Comment by DarwinBaker** [comment]
This is an excellent idea. I'll make sure to add an option for this in a future release (probably in the "tracker" settings tab). It'll include a textbox where you can enter an override name, then the tracker will exclude everyone else's progress. Thanks for the suggestion!

**Comment by DarwinBaker** [comment]
This has finally been added as of version 1.4.3.0!
