### ISSUE TITLE
Add the possibility to specify a folder for SFTP

### ISSUE THREAD

**Issue by Lauriichan** [DarwinBaker/AATool#19]
Currently I'm facing a small problem.
I wanted to use the AATool to track my advancement progress on my minecraft server which is installed on linux KVM.
The problem here is that the server is not installed in the home of the user which is used to log into the SFTP server.
Therefore I'm unable to use the AATool.
Would it be possible to add the possibility to specify the path to the root of the server?

**Comment by DarwinBaker** [comment]
Honestly not sure how it didn't occur to me to do this from the beginning. I'll make sure to add this as an option, it should be pretty straightforward to implement

**Comment by DarwinBaker** [comment]
Feature implemented in version 1.4.0.2
