### ISSUE TITLE
Noob

### ISSUE THREAD

**Issue by Opaxay** [DarwinBaker/AATool#2]

**Comment by Opaxay** [comment]
Bonjours je suis nouveau sur GitHub quand j'installe le fichier ZIP je ne trouve pas le fichier .exe vous aller surement me prendre pour un noob ou un boomer mais je ne sais pas si installer le fichier était la bonne chose à faire

Cordialement

**Comment by DarwinBaker** [comment]
Les salutations! Je ne connais pas beaucoup le français et j'ai dû utiliser google translate alors j'espère que ce message aura du sens lol.

Le moyen le plus simple d'installer l'outil est d'exécuter le "Setup.exe". Cela téléchargera et installera automatiquement tout ce dont vous avez besoin dans le dossier où vous l'avez exécuté.

Je vous recommande de créer un nouveau dossier quelque part comme votre bureau ou vos documents, de copier le "Setup.exe" dedans, puis de l'exécuter. J'espère que cela vous aidera, et s'il vous plaît laissez-moi savoir si vous rencontrez toujours des problèmes. Bienvenue dans la communauté All Advancements!

**Comment by Opaxay** [comment]
Thank you for your efforts even though you are not French it worked
PS: I also use Google Translate
