### ISSUE TITLE
Allow it to work on a server

### ISSUE THREAD

**Issue by CreeperNinjaYT** [DarwinBaker/AATool#24]
It would be very nice if it would work on servers

**Comment by DarwinBaker** [comment]
There are already a few ways to connect to a server! If it's a private server you can connect directly using your SFTP login, but I'm assuming based on your question that you're probably talking about a public server. If that's the case, this should be exactly what you're looking for:
https://github.com/fxmorin/Client_AATool

It's a fabric mod that you put in your mods folder, and it just takes the advancement data the server sends to the game client and saves it to a folder that AATool can be pointed to. The instructions on that page are pretty clear, but feel free to let me know if you need help with anything else. Best of luck!

**Comment by CreeperNinjaYT** [comment]
Yes, that is exactly what I was looking for, thought it does not seam to be making the "client_aatool" folder as it says it is meant to do, even after "/aatool true" is done, still no folder created

**Comment by DarwinBaker** [comment]
I haven't used this mod myself and I haven't looked at how exactly it works, so if you followed their instructions and it's not creating the folder I'd recommend asking about it on their GitHub, and hopefully you can get a more helpful answer than what I can provide. Best of luck!
