### ISSUE TITLE
"The Pillager" advancement frame wrong

### ISSUE THREAD

**Issue by TheEmptyDuckstache** [DarwinBaker/AATool#25]
I switched my frame style to "Minecraft" in settings and I found out "Who's The Pillager Now?" advancement used wrong frame("The Pillager" is an advancement and it is not a challenge)
![advancement](https://user-images.githubusercontent.com/70044919/159908537-94f7275f-2f5e-468f-ab44-30b62c34b056.png)

**Comment by DarwinBaker** [comment]
Thanks for pointing this out, this has now been fixed :)
