### ISSUE TITLE
1.11.2 all achievements adventuring time biomes not tracking

### ISSUE THREAD

**Issue by k4yfour** [DarwinBaker/AATool#31]
![image](https://user-images.githubusercontent.com/29940046/162746157-c0cec717-cdf3-470f-8a32-5cb7ea4c6cde.png)
everything else seems to track fine other than biomes. using 1.4.2.4
stats file:
[627c399d-0d0c-4931-8905-bac47287d4a3.zip](https://github.com/DarwinBaker/AATool/files/8464335/627c399d-0d0c-4931-8905-bac47287d4a3.zip)

**Comment by DarwinBaker** [comment]
This has now been fixed in release 1.4.3.0
