### ISSUE TITLE
Feature request: Allow combining select advancments that are usually done simlutaneously.

### ISSUE THREAD

**Issue by Civitello** [DarwinBaker/AATool#33]
Current Behaviour:
All advancements are displayed and recorded separately.

Desired behaviour:
An option to combine selected advancements is present that when selected will display either the harder/second advancement or display them both as a single item.

Reasoning:
There are a lot of advancements present in the overlay for most of the run, reducing the amount can make for a quicker time to figure out how the run is progressing.

Example Combinations:
Free the End / The Next Generation
Spooky Scary Skeleton / Skulls Collected
Bring Home the Beacon / Beaconator
A Furious Cocktail / How Did We Get Here?
A Throwaway Joke / Very Very Frightening

Combining just these 5 Pairs will reduce the count of advancements at the start by 6.25%.

**Comment by DarwinBaker** [comment]
Finally added a dedicated layout with redundant advancements hidden, reduced from 78 down to 35. To check it out just set layout to "optimized" in main application settings
