### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Kuzeyli35** [DarwinBaker/AATool#36]
[crash_report_2022_5_02_11_55_10.txt](https://github.com/DarwinBaker/AATool/files/8605976/crash_report_2022_5_02_11_55_10.txt)
when i start the aatool.exe for the first time it stays like this. it detects that i am entering the game but only the title changes
![Ekran görüntüsü 2022-05-02 225412](https://user-images.githubusercontent.com/70401893/166326632-59accefa-1570-456d-9ce3-8d88e6c1f80d.png)
gray part changes color over time(green-red from right-bottom corner).

**Comment by DarwinBaker** [comment]
Have you attempted this troubleshooting step outlined in the [FAQ?](https://github.com/DarwinBaker/AATool#faq)
![image](https://user-images.githubusercontent.com/51175243/166334767-b9aec9cc-3877-457a-9961-e6fe0dd0ed8a.png)

**Comment by Kuzeyli35** [comment]
Yes

**Comment by Kuzeyli35** [comment]
in 1.4.4.0 problem is solved
