### ISSUE TITLE
Cat ID Rename

### ISSUE THREAD

**Issue by TrainstTeki** [DarwinBaker/AATool#37]
From 1.19 Pre 1,The ID of the british cat variant has been renamed to "british_shorthair".As a result,the british cat variant in catalogue  cannot be displayed normally.
![Desktop Screenshot 2022 05 23 - 13 30 01 03](https://user-images.githubusercontent.com/70044919/169749892-f7d931d0-4451-48dc-b940-afae13b2ccd1.png)

**Comment by DarwinBaker** [comment]
Thanks for pointing this out, this will be updated when I replace "22w15a" with "1.19"
