### ISSUE TITLE
Application FPS cap applies to overlay

### ISSUE THREAD

**Issue by Civitello** [DarwinBaker/AATool#38]
When FPS cap under the application tab cap is changed the FPS of the overlay is capped. Please comment with a ? if a better report is required.

**Comment by DarwinBaker** [comment]
This is the intended (and required) functionality. All screens are tied to the same render loop for performance reasons. The point of the fps cap is for people on really old/slow laptops and stuff like that who need to squeeze out every ounce of performance they possibly can. Making the overlay still run at 60fps would require two separate render loops, defeating the whole purpose of this setting as a performance boost
