### ISSUE TITLE
Suggestion for reading Custom Advancements

### ISSUE THREAD

**Issue by Ayxenx** [DarwinBaker/AATool#39]
Would it be possible for this to read custom advancements in the future?

**Comment by Tatertot5s** [comment]
If you are doing custom advancements, i would recommend using a mod. unless its a competition of some sorts then you can use it. Here is a forge version: https://www.curseforge.com/minecraft/mc-mods/advancements-tracker (idk if this one works i have never used it) and here's a fabric version: https://www.curseforge.com/minecraft/mc-mods/advancementinfo (i know that this one works with custom advancements)
