### ISSUE TITLE
Can't download! Please help!

### ISSUE THREAD

**Issue by Dreadzillla** [DarwinBaker/AATool#44]
Hey there!
I love the idea of this tool and think it's so cool that you've done this as a project that you offer to the community for free! So thank you for that!

I'm trying to download it but keep getting stuck at the same point. I'm using a Dell Vostro 3360 laptop (2009?) running Windows 7 (yes, rather old, definitely NOT a gaming laptop, and it struggles a bit with Minecraft, but it's so worth it!).

I've used your link and video to get to the "Assets" menu where I select "Setup.exe". No issues up to this point! The Setup.exe file downloads and I tell it to "run" (I get two pop-ups asking me to run or cancel - one coming from my user downloads\setup.exe file, and the other coming from my user AppData\Local\Temp\Setup.exe - I tell them both to run).

The AATool Update Assistant opens, as it does in your setup guide video, but this is where the issue lies. The top message in this download window says "Checking for updates..." while the bottom message is stuck on "Parsing GitHub releases" instead of loading through all of the file components like in your video. The "Current Task" is at 100% and the "Overall Progress" is at 25% but nothing continues at this point, regardless of how long I leave it to load.

I have tried starting from scratch multiple times, deleting the setup.exe file and starting again, selecting the setup.exe file from my downloads file and telling it to run from here instead of the downloads menu that pops up at the bottom of the webpage, checking my antivirus settings and adding the setup.exe file to the "allow" list. I'd say I'm _fairly_ tech savvy (of course, not to your level!) but this about exhausts my limited knowledge of how to go about troubleshooting the issue myself!

I'll continue tinkering with it while I wait for your response, and any help would be greatly appreciated!

Thanks so much!
Natasha (aka Dreadzillla!)

**Comment by Dreadzillla** [comment]
Phew!
After all of that, I just managed to download the tool! I couldn't get the Setup.exe file to work (I'm still curious why that might be), but I figured out how to download the zip file and it seems to be working!
Every time I go to a different window and return to the AATool, the icons and descriptions gradually shift/stretch out of frame, with the biggest stretching being more noticeable toward the right side of the screen (the items along the left of the page don't shift as far as those on the right, gradually increasing the degree of shift from left to right, if that makes sense!). If I move the window, they centre again. Is there a way to fix that on my end?

**Comment by DarwinBaker** [comment]
Hey, glad to hear you got it working! The installer hasn't been developed for or tested on windows 7, so my best guess is that it has something to do with that. 

As for the visual bug you're describing it's hard to be sure, but I wouldn't be surprised if it has something to do with the intel integrated graphics in your laptop. Would you mind attaching one or more screenshots of the problem you've described? Maybe I can figure out what's happening and see if it's fixable. That being said, windows 7 isn't an officially targeted platform so I can't guarantee I'll be able to reproduce the issue or fix it, but it's certainly worth a shot

**Comment by Dreadzillla** [comment]
Hey there! Thanks for your response!
That makes sense then! I will attach screen shots from:
1. When it is empty, but centred
2. When I first open the program (it is off centre in this picture)
3. When my achievements are updated and centred, and
4. When my achievements are updated, but off centre.

It is easy to correct on my end, just by dragging the window slightly left or right, but I thought it was worth mentioning!

![AATool - empty, but centred](https://user-images.githubusercontent.com/108196359/176754379-37231c1b-11e7-41b8-b5c2-840431d09a61.png)
![AATool - initial open](https://user-images.githubusercontent.com/108196359/176754384-b75b185d-6584-4ab1-af1b-37ff4710cd9c.png)
![AATool - updated and centred](https://user-images.githubusercontent.com/108196359/176754386-2e397450-bb1b-4414-bad8-47d0afe6fd3f.png)
![AATool - updated, off centre](https://user-images.githubusercontent.com/108196359/176754392-3b1a9dd9-69bf-4205-9f6d-816b5f433ed2.png)

**Comment by DarwinBaker** [comment]
Upon first glance it looks like your screen might be too small for the "relaxed" view mode which can cause Windows to force the window smaller and break some stuff graphically. All the icons that appear offset are on the foreground layer, so that would make sense. I'll look into finding a way to keep it from doing that, but in the meantime could you try setting the application view mode to "compact" and seeing if it fixes the issue?
![image](https://user-images.githubusercontent.com/51175243/176776882-7b533ba9-79c6-4efa-8d48-5e16e1e19265.png)

**Comment by Dreadzillla** [comment]
Oops! When I was using it before I had it set to compact, but I guess it reset when I closed it.
Here are the screenshots for the compact setting, both centred and off-centre, without my updated achievements. It doesn't seem to save the achievements when I don't have Minecraft running. Is that meant to be the case?
The shift off-centre is less extreme in the compact version, and here you can see what I was meaning about the degree of shift increasing from the achievement icons/descriptions on the left to those on the right. Like with the relaxed setting, in compact the icons return to off-centre when I initially open the tool and when I return to it from another window, or after minimizing the tool window. Likewise, the icons return to centre when I drag the tool window slightly in any direction.
This is honestly just a minor inconvenience and I wouldn't want to take your attention away from more important work! Especially if the issue is just that I'm trying to use the tool on an old, non-gaming laptop running Windows 7!

![AATool - compact   centred](https://user-images.githubusercontent.com/108196359/176940127-2e17efb8-75d7-4cc5-b797-7e5e4274b5b8.png)
![AATool - compact   off centre](https://user-images.githubusercontent.com/108196359/176940159-720b4915-6105-4633-a1ef-0f880ebd65c3.png)
