### ISSUE TITLE
Adventure Time and Hot Tourist Destination not working

### ISSUE THREAD

**Issue by BeardoBaggins** [DarwinBaker/AATool#46]
Hello, I'm having trouble getting the Adventure Time and Hot Tourist Destinations to track the biomes I visited. Everything seems to be working fine except for those two. <img width="818" alt="Screenshot" src="https://user-images.githubusercontent.com/108590217/177012799-88f041ab-43eb-43ca-abe7-eda7ac54cd2a.png">

**Comment by BeardoBaggins** [comment]
Nevermind, I got rid of the of the Blaze and Caves Data pack and now its working. Not sure why that would cause issues.

**Comment by DarwinBaker** [comment]
I had blaze and caves on my 1.16 survival world and I noticed this as well (although on 1.16 the only one that didn't work was the nether biomes)

My assumption is that BaC overrides/changes some of the advancement ID's. The advancements themselves should still track as complete/incomplete, I believe it's just the biomes themselves that don't work. 

If you're playing blaze and caves with fabric and want help keeping track of your stuff I can highly recommend this mod:
https://www.curseforge.com/minecraft/mc-mods/advancementinfo
