### ISSUE TITLE
Installation cannot be Verified?

### ISSUE THREAD

**Issue by banarlie** [DarwinBaker/AATool#47]
I downloaded the setup, Clicked run both times, the set up runs pauses at 25% then skips to 100 sating installation cannot be verified and to restart the computer or manually install :/ I've restarted 3 times and downloaded the zip and its still not working.

**Comment by DarwinBaker** [comment]
Have you tried running Setup.exe as administrator? Also getting the setup executable to run isn't necessary, you can just extract the zip to a folder manually. What did you do after downloading the zip, and what exactly doesn't work about extracting it and running AATool.exe?
