### ISSUE TITLE
Suggestion for a program for randomized loot/recipe challenges

### ISSUE THREAD

**Issue by derekantrican** [DarwinBaker/AATool#49]
Tempted to make this myself as a WinForms/WPF dev & MC player, but don't have the time. Feel free to close & ignore this request if you feel the same.

It's not as popular now, but people still occasionally do the "randomized loot drops"/"randomized crafting" challenges. A companion program (like AATool) where someone can quickly enter "gold block -> oak sapling" or whatever and have the program track the trees/cycles could be handy for people like CaptainSparklez who still do those challenges. A lot of players keep things like a Google Doc/notepad anyway to write this stuff down so this could be a bit more user-friendly way to do it (especially if it can help you see intersections in patterns that you didn't think of).

Obviously there'd be a way for the program to dig through the datapack files & get all the mappings (which would be cheating to just display them all) but maybe there's a way for the program to see if the player has "unlocked"/"discovered" that loot drop/crafting recipe and display it automatically (so the player doesn't have to stop to write it down).

Anyway, just an idea. Feel free to close out and ignore.

**Comment by Tatertot5s** [comment]
I know ppl dont like work, but you can make a exell sheet and do it yourself. just a suggestion, on a solution but if someone made this it would be cool!
