### ISSUE TITLE
Installation or update deletes other files in folder

### ISSUE THREAD

**Issue by PacoRmzA** [DarwinBaker/AATool#5]
Hi! I just installed the tool using the exe, but now all of my profiles in .minecraft/versions are gone. Not only that, but after I moved AATool.exe and AAUpdate.exe to my Desktop and ran the latter just in case, practically all of my files and shortcuts disappeared. I tried restarting, without any luck.

**Comment by DarwinBaker** [comment]
This issue has been fixed as of version 1.2.5.2. AATool was designed to be run inside its own self-contained folder, however you can now run it anywhere and it will no longer mess up unrelated files. Thanks for pointing this out, and my sincerest apologies for the inconvenience. Hopefully you have a backup of anything important, but if not I recommend running [file recovery software](https://www.ccleaner.com/recuva).
