### ISSUE TITLE
Changing settings and it kind of killed itself

### ISSUE THREAD

**Issue by YouTuner** [DarwinBaker/AATool#56]
I ain't quite sure what I did but I was just changing settings in the program and then it crashed.
Log files attached
[logs.zip](https://github.com/DarwinBaker/AATool/files/10070411/logs.zip)

**Comment by DarwinBaker** [comment]
This issue has been fixed in release 1.5.2.0. If your AATool won't start you can just run AAUpdate.exe and the new update will be automatically installed
https://github.com/DarwinBaker/AATool/releases/tag/v1.5.2.0-release
