### ISSUE TITLE
SFTP Not working on a local server on Windows 10

### ISSUE THREAD

**Issue by Maartincm** [DarwinBaker/AATool#62]
I download the source code and debugged a little.

Apparently there is an incompatibility for Windows in how the paths are being crafted (both for getting the last write time of `level.dat` and downloading the `stats` and `advancements` folders).

My guess is that the usage of `/` (forward slash) manually in some of the paths crafting is breaking on Windows servers. Maybe people is not complaining because popular hostings run on Linux (?)

I will create a Pull Request with the changes that made my instance work but It's up to you to test if the changes won't break anything in the usual SFTP environments.

Edit: Also I was a bit confused because the advancements were not being updated but there was no error in the UI. Maybe We should add a big try-catch block wrapping the entire thread subroutine that is doing the SFTP syncing and errors like this could be printed.

**Comment by DarwinBaker** [comment]
Just incorporated those changes into the new version, would you mind double checking that your server is now tracked properly on version 1.6.0.1?

**Comment by Maartincm** [comment]
@DarwinBaker 
Yup! 1.6.0.1 is working properly in my setup.

**Comment by DarwinBaker** [comment]
Good to hear
