### ISSUE TITLE
1.6.0.0 crashes when launching

### ISSUE THREAD

**Issue by Johnden1** [DarwinBaker/AATool#66]
Getting this crash report. (since it's in my system language, it states that a file aatool_test.json cannot be found)
[crash_report_2023_3_03_6_14_09.txt](https://github.com/DarwinBaker/AATool/files/10884649/crash_report_2023_3_03_6_14_09.txt)

**Comment by DarwinBaker** [comment]
Thanks for pointing this out, I just released a hotfix that removes a line of test code that was causing the problem
