### ISSUE TITLE
Can't get the overlay to show up

### ISSUE THREAD

**Issue by Brody0727** [DarwinBaker/AATool#70]
When I add the overlay in OBS, it appears on OBS's monitor, but not on my computer. The screen overlay also won't lock on my screen. Please respond ASAP.

**Comment by DarwinBaker** [comment]
I'm slightly unclear as to what you mean by it showing on obs but "not on your computer". Do you mean over the game window while you're playing it? If so that's not how it works, it's supposed to only be used for obs. Also what do you mean by "lock on your screen"?
