### ISSUE TITLE
All Blocks not detecting Oak Hanging Signs

### ISSUE THREAD

**Issue by Lino5000** [DarwinBaker/AATool#73]
I'm using the tracker for a casual playthrough of 1.20 All Blocks, and I've just discovered that it doesn't seem to properly detect when I place a hanging sign. The "times used" statistic is present and greater than 0, but it doesn't become highlighted in the tracker.

After some investigation myself, I *think* the issue comes down to [this XML tag](https://github.com/DarwinBaker/AATool/blob/v1.6.3.1-revision/AATool/assets/objectives/1.20/blocks.xml#L794C10-L794C35) being `oak_hanging_hanging_sign` instead of just `oak_hanging_sign`, but I'm not sure how to test that.

**Comment by Lino5000** [comment]
Update: I figured out how to test it, and changing that line does seem to resolve the issue! Shall I make a PR for it?

**Comment by DarwinBaker** [comment]
Thanks for pointing this out! I was about to release a new update anyway, so I've added this fix as well. There's no need to do anything else on your end.
