### ISSUE TITLE
Very sluggish UI

### ISSUE THREAD

**Issue by meza** [DarwinBaker/AATool#82]
Hey,

I've just installed the app on Win11 with 4K screens and the app seems very unresponsive. Even just getting to the settings, I have to hover over the settings button for 30 seconds for it to get highlighted and then once I press it, I can only hope it got registered.

Any idea what's going on?

**Comment by DarwinBaker** [comment]
What does your utilization look like for AATool in task manager? Also what graphics card are you running?

**Comment by meza** [comment]
2080ti and the utilisation was normal.
The funny thing is that after a 3rd restart and enabling the overlay, it's working normally. I'm not sure what the mishap was :/
