### ISSUE TITLE
Can't Interact With Anything After Setting AATool to Track All Blocks

### ISSUE THREAD

**Issue by AceUpthe5leeve** [DarwinBaker/AATool#85]
Pretty much what it the title says. Once I turned the tool to track all blocks, the intro window cannot be interacted with, I have tried both restarting my laptop and deleting and reinstalling it. Restarting my laptop did nothing and while reinstalling it allowed me to once again interact with all advancements, the second I click All Blocks, I have to delete and reinstall it. I don't know whether it's a user-error or a bug.

**Comment by DarwinBaker** [comment]
Do you mean you can't click anything after? Can you send a screenshot of the all blocks page? Can you still open the settings menu by pressing escape? You shouldn't have to uninstall and reinstall to switch back to all advancements.

**Comment by AceUpthe5leeve** [comment]
I can still open the settings window, thankfully, but I can't click on either of the buttons on the welcome menu. A screenshot doesn't include the mouse, but it is hovering over the "Not now, Thanks!" button.
[image](https://github.com/DarwinBaker/AATool/assets/156559601/b2e34e0b-cd99-49dd-b5a7-7a03fe4fe778)

**Comment by DarwinBaker** [comment]
Are you able to click either the "Settings" or the "MCSR Community" buttons on all advancements mode or do no buttons work at all?

**Comment by AceUpthe5leeve** [comment]
No, I can't even see those buttons no matter how much I move my screen around. The only button I can see is the "Rules/Help" button, which I can't interact with either.

**Comment by DarwinBaker** [comment]
I mean this button on the all advancements tracker, not all blocks
![image](https://github.com/DarwinBaker/AATool/assets/51175243/af482d4a-97df-4010-84a9-fcf7f4e75edd)

**Comment by AceUpthe5leeve** [comment]
Ah, no, I can't get it to show anything more than this
![image](https://github.com/DarwinBaker/AATool/assets/156559601/d8fc63ee-e5bc-4344-b6b0-9db6d25669d6)
.

**Comment by DarwinBaker** [comment]
Ah I see, you'll have to set it to relaxed or optimized layout to show that one. I see the settings button in the bottom left though, does that one not work either?

**Comment by AceUpthe5leeve** [comment]
I can interact with the settings button in compact mode, but I can't even see it in the other three. And I can click the MCSR button on the other three, but I haven't found a way to get out of it without restarting the program.
