### ISSUE TITLE
Is FTP supported?

### ISSUE THREAD

**Issue by Endrock6** [DarwinBaker/AATool#86]
I use my server through the server host Shockbyte. All of their servers use just basic FTP and not SFTP. I'm not sure if they are compatible, but this error isn't encouraging. I don't really know how FTP works but I'm hoping this can be resolved
![image_2024-02-06_172531821](https://github.com/DarwinBaker/AATool/assets/101973300/0c15bbbc-a67c-4347-92fb-8281a0797ba9)

**Comment by Endrock6** [comment]
Also this looks like a link but doesn't do anything
![image_2024-02-06_172949305](https://github.com/DarwinBaker/AATool/assets/101973300/6e5482e4-8c8a-42e5-84a0-c77598a8b2d1)

**Comment by DarwinBaker** [comment]
FTP is not currently supported. I may add support for it in the near future given how many people have been asking about it recently, but no guarantees on when this will be.

**Comment by Endrock6** [comment]
Please do add FTP support. Without it the app is rendered useless to me since my computer isn't powerful enough to host my own world at 60fps and my host doesn't support SFTP.
