### ISSUE TITLE
connect sftp to minehut

### ISSUE THREAD

**Issue by westnew** [DarwinBaker/AATool#87]
I am trying to sftp to my server on Minehut but keeps getting error parsing server properties it says no such file and keeps retrying.

**Comment by Gills2794** [comment]
sounds similar to this previous issue:

https://github.com/DarwinBaker/AATool/issues/78

**Comment by DarwinBaker** [comment]
I've added the option to manually specify if your host is Windows or Linux and fixed the path formatting.
