### ISSUE TITLE
Aternos not working with AATool

### ISSUE THREAD

**Issue by TheRoundestFella** [DarwinBaker/AATool#88]
Aternos is a server runner for people like me who don't want to pay for a server. Sadly, I cannot seem to get the correct IP address to satisfy the Co-op setup assistant. Aternos doesn't allow you to see the SFTP for safety reasons. Anybody got an idea?

**Comment by DarwinBaker** [comment]
The co-op setup is for syncing your tracker's progress with another player's tracker when you're hosting from LAN (for co-op speedrunning purposes). It's unrelated to using SFTP for connecting to a minecraft server directly. 

SFTP credentials are required in order for the tracker to connect to the server and download your progress. If the host, in this case Aternos doesn't provide them, then unfortunately there's no way for the tracker to access your progress. If you want to use AATool with a minecraft server, you'll have to choose a different host that does provide SFTP access
