### ISSUE TITLE
AATool not even launching

### ISSUE THREAD

**Issue by PotatoNooob** [DarwinBaker/AATool#89]
Every time I try to open it nothing happens.

Here are my logs: 
-
OS: Microsoft Windows 10 Pro
Architecture: 64-bit
Exception: The type initializer for 'AATool.Net.OpenTracker' threw an exception.

    at AATool.Net.OpenTracker.Update(Time time)

    at AATool.Main.Update(GameTime gameTime)

    at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)

    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)

    at AATool.Program.Main()

**Comment by DarwinBaker** [comment]
Have you tried deleting the config folder? If that doesn't work then try reinstalling if you haven't already

**Comment by PotatoNooob** [comment]
I deleted the config folder and I'm still getting the same issue. Also, I already tried reinstalling multiple times.

**Comment by DarwinBaker** [comment]
I'm not sure exactly what's causing the crash, but the feature that it's occurring within is currently unused so I'll remove the code for it and release a patch. I'll comment on here to let you know when the patch has been released so you can download and try the new version.

**Comment by DarwinBaker** [comment]
Hey, I just released an update that should fix this issue. Would you mind letting me know if it launches now?

**Comment by PotatoNooob** [comment]
Hello! I just downloaded the new release and it works just fine. Thank you for helping me

**Comment by DarwinBaker** [comment]
Glad to hear it!
