### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by PistonUser** [DarwinBaker/AATool#9]
is there any way i can compile this for linux?
Edit: Do you think the tool would work for linux?
Edit3: I don't think wine works for this stuff where it reads outside files
Edit4: Yes there was an Edit2

**Comment by nael572** [comment]
````
how did I pies IWHAUDWYSWI
````

**Comment by PistonUser** [comment]
> ````
> how did I pies IWHAUDWYSWI
> ````

What?

**Comment by DarwinBaker** [comment]
AATool is based on the Monogame framework which does support Linux compilation, but the multi-window system relies on some specific directx stuff that I'm pretty sure is windows only. I'll do some testing on my mint vm when I get the chance and see if I can get something working though!

**Comment by PistonUser** [comment]
> AATool is based on the Monogame framework which does support Linux compilation, but the multi-window system relies on some specific directx stuff that I'm pretty sure is windows only. I'll do some testing on my mint vm when I get the chance and see if I can get something working though!

Ok Tysm Im pretty sure directX is Windows only tho
