### ISSUE TITLE
i can't open AATool :/

### ISSUE THREAD

**Issue by funkyexe** [DarwinBaker/AATool#92]
![image](https://github.com/DarwinBaker/AATool/assets/139810876/fd15069e-f5c5-4a4f-b053-7b970145f7bf)

i tried a few things, such as reinstalling, updating java etc. but there is still the same problem. how can i solve it?

**Comment by berkaygk** [comment]
same thing

**Comment by DarwinBaker** [comment]
This has now been fixed in update 1.7.5.0

**Comment by mtunag** [comment]
> This has now been fixed in update 1.7.5.0

u a great man my friend, u a great man.
