### ISSUE TITLE
Is AATool safe?

### ISSUE THREAD

**Issue by minecraftdudethatplaysminecraft** [DarwinBaker/AATool#93]
Everytime time i try to open AATool it says: Windows protected your PC
![image_2024-06-12_101253467](https://github.com/DarwinBaker/AATool/assets/172482553/2e8a02be-aafb-4ef1-b6e0-f93c38acb8d8)

**Comment by DarwinBaker** [comment]
Yes, AATool is safe as long as you downloaded it from here, the patreon, or the setup exe. Please check the installation section of the readme, there's a section detailing that "You will likely run into a Windows SmartScreen pop up stating "Windows protected your PC" when you first run the program. You can safely ignore this and click "Run Anyway" and it shouldn't ask again."
